<a href="https://colab.research.google.com/github/doriller/pytorch_shoeisha/blob/3/Lesson3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import torch

a = torch.tensor([1,2,3])
print(a, type(a))

print('--------- 2次元のリストから生成 ------------')
b = torch.tensor([
    [1,2],
    [3,4]
])
print(b)

print('--------- dtypeを指定して倍精度のTensorにする ----------')
c = torch.tensor([
    [1,2],
    [3,4],
], dtype=torch.float64)
print(c)

print('---------- 0から9までの数値で初期化 -----------')
d = torch.arange(0, 10)
print(d)

print('---------- 全ての値が0の2 x 3のTensor ----------')
e = torch.zeros(2, 3)
print(e)

print('--------- 全ての値が乱数の2 x 3のTensor ---------')
f = torch.rand(2, 3)
print(f)

print('--------- Tensorの形状はsizeメソッドで取得 --------')
print(f.size())

print('--- -5から5までの連続値を10生成 ---')
g = torch.linspace(-5, 5, 10)
print(g)

print('--- Tensor -> Numpy ---')
h = torch.tensor([
    [1, 2],
    [3, 4],
])
hh = h.numpy()
print(hh)

print('--- Numpy -> Tensor ---')
k = torch.from_numpy(hh)
print(k)

m = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
])

print('--- 2つのインデックスを指定 ---')
print(m[0, 1])

print('--- 範囲を指定 ---')
print(m[1:2, :2])

print('--- リストで複数のインデックスを指定 ---')
print(m[:, [0, 2]])

print('--- 3より大きい要素のみを指定 ---')
print(m[m > 3])

print('--- 要素を変更 ---')
m[0, 2] = 11
print(m)

print('--- 要素の一括変更 ---')
m[:, 1] = 22
print(m)

print('--- 10より大きい要素のみ変更 ---')
m[m > 10] = 33
print(m)

#********************** 3.2.5 ****************************************


tensor([1, 2, 3]) <class 'torch.Tensor'>
--------- 2次元のリストから生成 ------------
tensor([[1, 2],
        [3, 4]])
--------- dtypeを指定して倍精度のTensorにする ----------
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
---------- 0から9までの数値で初期化 -----------
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
---------- 全ての値が0の2 x 3のTensor ----------
tensor([[0., 0., 0.],
        [0., 0., 0.]])
--------- 全ての値が乱数の2 x 3のTensor ---------
tensor([[0.8554, 0.4193, 0.7068],
        [0.5198, 0.9419, 0.8803]])
--------- Tensorの形状はsizeメソッドで取得 --------
torch.Size([2, 3])
--- -5から5までの連続値を10生成 ---
tensor([-5.0000, -3.8889, -2.7778, -1.6667, -0.5556,  0.5556,  1.6667,  2.7778,
         3.8889,  5.0000])
--- Tensor -> Numpy ---
[[1 2]
 [3 4]]
--- Numpy -> Tensor ---
tensor([[1, 2],
        [3, 4]])
--- 2つのインデックスを指定 ---
tensor(2)
--- 範囲を指定 ---
tensor([[4, 5]])
--- リストで複数のインデックスを指定 ---
tensor([[1, 3],
        [4, 6]])
--- 3より大きい要素のみを指定 ---
tensor([4, 5, 6])
--- 要素を変更 ---
tensor([[ 1,  2, 11],
        [ 4,  5,  6]])
--- 要素の一